name: CI
on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  archive:
    name: Archive Ckt
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: zip -Z deflate ieee13.ckv *.csv *.json README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: ckv
          path: ieee13.ckv

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions: write-all
    needs: [ archive ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ckv

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Ckv artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ieee13.ckv
          asset_name: ieee13-${{ github.ref_name }}.ckv
          asset_content_type: application/zip
